server:
  port: 8888
spring:
  application:
    name: ca-product
  datasoruce:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    show-sql: true
    hibernate:
#      type: trace
      #      hbm2ddl:
      #        import_files: 'classpath:schema.sql'
      ddl-auto: none
      default_schema: product
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.H2Dialect
    # Enabling H2 Console
    # Custom H2 Console URL
  h2:
    console.enabled: true
    console.path: /h2

  main:
    #    banner-mode:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages

application-description: project.description
application-version: project.version
#    restart:
#      enabled: true
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate: info
#    org.hibernate.type: trace
    org.hibernate.stat: debug
  #root: ERROR
feign:
  hystrix:
    enabled: true